baseURL = "https://ecstatic-bardeen-6b79c6.netlify.app"
languageCode = "en-us"
title = "My New Hugo Site"

[permalinks]
    blog = "/:filename/"

  # See https://feathericons.com/
    # The value of pre is the icon name
    [menu]
      [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
      [[menu.main]]
        name = "Blog"
        pre = "edit"
        url = "/blog/"
        weight = 2
      [[menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/tags/"
        weight = 3

[taxonomies]
  tag = "tags"

[params]
    dateFormat = "Jan 2, 2006"
    homeText = "You just made a hugo blog from scratch."
